CREATE DATABASE IF NOT EXISTS encore
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE encore;

CREATE TABLE IF NOT EXISTS user_account (
  id VARCHAR(32) PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  role VARCHAR(32) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_account_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS encore_show (
  id VARCHAR(32) PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  subtitle VARCHAR(128) NOT NULL,
  cover_url VARCHAR(512) NOT NULL,
  description TEXT NOT NULL,
  duration INT NOT NULL,
  category VARCHAR(64) NOT NULL,
  tags JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_encore_show_category (category),
  INDEX idx_encore_show_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS show_schedule (
  id VARCHAR(32) PRIMARY KEY,
  show_id VARCHAR(32) NOT NULL,
  theater_name VARCHAR(128) NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL,
  price_range VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_show_schedule_show_time (show_id, start_time),
  CONSTRAINT fk_show_schedule_show
    FOREIGN KEY (show_id) REFERENCES encore_show (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
